version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile-http
    ports:
      - "8080:8080"

  script:
    build:
      context: .
      dockerfile: Dockerfile-script
